#ifndef STUDENTRECORDSYSTEM_AUTHENTICATION_H
#define STUDENTRECORDSYSTEM_AUTHENTICATION_H

void BAUTHENTICATION_checkAdminPassword();
void BAUTHENTICATION_checkStudentPassword();

#endif //STUDENTRECORDSYSTEM_AUTHENTICATION_H
