#ifndef STUDENTRECORDSYSTEM_MEMORY_MANAGEMENT_H
#define STUDENTRECORDSYSTEM_MEMORY_MANAGEMENT_H

void DMEMORY_freeStudent(Student* student);
void DMEMORY_allocateStudent();

#endif //STUDENTRECORDSYSTEM_MEMORY_MANAGEMENT_H
